tenant:
  name: TENANT

xdbFederation:
  name: animal
  password: test
  uri: xhive://localhost:2910

xdbDatabase:
  name: animal
  password: test

application:
  name: Animals
  description: Sample application
  category: Sample category

holding:
  name: Animals

aic:
  name: Animals
  criteria:
    name: animalName,filePath
    label: Animal Name,File Path
    type: STRING,STRING
    pkeyminattr: ","
    pkeymaxattr: ","
    pkeyvaluesattr: ","
    indexed: true,true

namespace:
  prefix: n
  uri: urn:opentext:ia:schema:sample:animal:1.0
  
query:
  name: DefaultQuery
  xdbpdis:
  - entity:
      path: /n:animals/n:animal
    template: return $aiu
    operands:
    - name: animalName,filePath
      path: n:animal_name,n:file_path
      type: STRING,STRING
      index: true,true

quota:
  name: DefaultQuota

resultHelper:
  name: result_helper
  content:
    format: xml
    resource: DefaultResultHelper.xml

search:
  Find animals:
    nested: false
    state: DRAFT
    inuse: true
    compositions:
    - name: Set 1
      xform:
        name: form
        content:
          format: xml
          resource: FindAnimals.form.xml
      result:
        main:
          name: animalName,filePath
          label: Animal Name,File Path
          path: n:animal_name,n:file_path
          type: STRING,STRING
          sort: NONE,NONE

retention-policy:
  name: Animals

pdiSchema:
  content:
    format: xsd
    resource: pdi-schema.xsd

pdi:
  name: Animals-pdi
  content:
    format: xml
    resource: pdi.xml

ingest:
  content:
    format: xml
    resource: ingest.xml

fileSystemFolder:
  name: Animals-folder
  subPath: stores/file_store_01

store:
  name: file_store_01

retentionPolicy:
  name: PhoneCalls-policy
  agingStrategy:
    type: duration
    agingPeriod:
      units: days
      value: 89
  dispositionStrategy:
    type: destroy all
 