anchored_name: &_name Animals
anchored_schema: &_schema "urn:opentext:ia:schema:sample:animal:1.0"

server:
  uri: http://localhost:8765/services
  authentication:
    token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjM2MDU4Mjg3NjEsInVzZXJfbmFtZSI6InN1ZUBpYWN1c3RvbWVyLmNvbSIsImF1dGhvcml0aWVzIjpbIkdST1VQX0FETUlOSVNUUkFUT1IiLCJHUk9VUF9SRVRFTlRJT05fTUFOQUdFUiIsIkdST1VQX0JVU0lORVNTX09XTkVSIiwiR1JPVVBfRU5EX1VTRVIiLCJHUk9VUF9ERVZFTE9QRVIiLCJHUk9VUF9JVF9PV05FUiIsIlJPTEVfQURNSU5JU1RSQVRPUiIsIlJPTEVfUkVURU5USU9OX01BTkFHRVIiLCJST0xFX0JVU0lORVNTX09XTkVSIiwiUk9MRV9FTkRfVVNFUiIsIlJPTEVfREVWRUxPUEVSIiwiUk9MRV9JVF9PV05FUiJdLCJqdGkiOiJiODhmMGEwMi0yNTMyLTQ2OWUtYmU4ZC1iYWVkZjM5OTExNDIiLCJjbGllbnRfaWQiOiJpbmZvYXJjaGl2ZS5pYXdhIiwic2NvcGUiOlsiYWRtaW5pc3RyYXRpb24iLCJjb21wbGlhbmNlIiwic2VhcmNoIl19.tRNjesTSzMYmpFNP1xCPl_SHUetGtLvyHzvc59TCqF0

tenant: TENANT

xdb:
  federation:
    name: animal
    password: test
    uri: xhive://localhost:2910
  database:
    name: animal
    password: test

application:
  name: *_name
  description: Sample application
  category: Sample category

holding:
  name: *_name

aic:
  name: *_name
  criteria:
    name: "animalName,filePath"
    label: "Animal Name,File Path"
    type: "STRING,STRING"
    pkeyminattr: ","
    pkeymaxattr: ","
    pkeyvaluesattr: ","
    indexed: "true,true"

query:
  - name: DefaultQuery
    namespace:
      prefix: n
      uri: *_schema
    result:
      root:
        element: result
        ns-enabled: true
      schema: *_schema
    xdbpdi:
      entity:
        path: "/n:animals/n:animal"
      schema: *_schema
      template: "return $aiu"
      operand:
        name: "animalName,filePath"
        path: "n:animal_name,n:file_path"
        type: "STRING,STRING"
        index: "true,true"

quota:
  name: DefaultQuota

result-helper:
  - name: "result_helper"
    schema: *_schema
    xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <resultConfigurationHelper xmlns:n="urn:opentext:ia:schema:sample:animal:1.0" xmlns:ia="urn:x-emc:ia:schema:pdi">
        <element>
          <name>id</name>
          <label>ID</label>
          <type>ID</type>
          <path>@ia:id</path>
        </element>
        <element>
          <name>animalName</name>
          <label>Animal Name</label>
          <type>STRING</type>
          <path>n:animal_name</path>
        </element>
        <element>
          <name>filePath</name>
          <label>File Path</label>
          <type>STRING</type>
          <path>n:file_path</path>
        </element>
      </resultConfigurationHelper>

search:
  - name: "Find yaml animals"
    description: "Search animal"
    nested: false
    state: DRAFT
    inuse: true
    aic: *_name
    query: DefaultQuery
    composition:
      - name: "Set 1"
        xform:
          name: form
          xml: |
            <xhtml:html xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xforms="http://www.w3.org/2002/xforms"
                        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
              <xhtml:head>
                <xforms:model>
                  <xforms:instance xmlns="">
                    <data>
                      <animalName />
                      <filePath />
                    </data>
                  </xforms:instance>
                  <xforms:instance xmlns="" id="labels">
                    <labels>
                      <animalName>Animal Name</animalName>
                      <filePath>File Path</filePath>
                    </labels>
                  </xforms:instance>
                  <xforms:instance xmlns="" id="hints">
                    <hints>
                      <animalName />
                      <filePath />
                    </hints>
                  </xforms:instance>
                  <xforms:instance xmlns="" id="prompts">
                    <prompts>
                      <animalName />
                      <filePath />
                    </prompts>
                  </xforms:instance>
                  <xforms:instance xmlns="" id="alerts">
                    <alerts>
                      <animalName />
                      <filePath />
                    </alerts>
                  </xforms:instance>
                  <xforms:instance xmlns="" id="range-messages">
                    <rangemessages>
                      <animalName />
                      <filePath />
                    </rangemessages>
                  </xforms:instance>
                  <xforms:instance xmlns="" id="pattern-messages">
                    <patternmessages>
                      <animalName />
                      <filePath />
                    </patternmessages>
                  </xforms:instance>
                  <xforms:submission id="submit01" method="post" serialization="application/xml" />
                  <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xforms="http://www.w3.org/2002/xforms"
                              targetNamespace="http://www.w3.org/2002/xforms" elementFormDefault="qualified">
                  </xsd:schema>
                  <bind xmlns="http://www.w3.org/2002/xforms" ref="/data/animalName" />
                  <bind xmlns="http://www.w3.org/2002/xforms" ref="/data/filePath" />
                </xforms:model>
              </xhtml:head>
              <xhtml:body>
                <input xmlns="http://www.w3.org/2002/xforms" ref="filePath">
                  <label ref="instance('labels')/filePath" />
                  <hint ref="instance('hints')/filePath" />
                  <hint appearance="minimal" ref="instance('prompts')/filePath" />
                  <alert ref="instance('alerts')/filePath" />
                  <message class="range" ref="instance('range-messages')/filePath" />
                  <message class="pattern" ref="instance('pattern-messages')/filePath" />
                </input>
                <input xmlns="http://www.w3.org/2002/xforms" ref="animalName">
                  <label ref="instance('labels')/animalName" />
                  <hint ref="instance('hints')/animalName" />
                  <hint appearance="minimal" ref="instance('prompts')/animalName" />
                  <alert ref="instance('alerts')/animalName" />
                  <message class="range" ref="instance('range-messages')/animalName" />
                  <message class="pattern" ref="instance('pattern-messages')/animalName" />
                </input>
              </xhtml:body>
            </xhtml:html>
        result:
          main:
            name: "animalName,filePath"
            label: "Animal Name,File Path"
            path: "n:animal_name,n:file_path"
            type: "STRING,STRING"
            sort: "NONE,NONE"

retention-policy:
  name: *_name

pdi:
  schema:
    name: *_schema
    xsd: |
      <?xml version="1.0" encoding="UTF-8"?>
      <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
          targetNamespace="urn:opentext:ia:schema:sample:animal:1.0" xmlns:animal="urn:opentext:ia:schema:sample:animal:1.0">
        <xs:element name="animals">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" ref="animal:animal"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="animal">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="animal:animal_name"/>
              <xs:element ref="animal:file_path"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="animal_name" type="xs:string"/>
        <xs:element name="file_path" type="xs:string"/>
      </xs:schema>
  xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <datas>
      <data>
        <id>pdi.index.creator</id>
        <key.document.name>xdb.pdi.name</key.document.name>
        <indexes>
          <path.value.index>
            <name>animal_name</name>
            <path>/{urn:opentext:ia:schema:sample:animal:1.0}animals/{urn:opentext:ia:schema:sample:animal:1.0}animal/animal_name&lt;STRING>
            </path>
            <compressed>false</compressed>
            <unique.keys>false</unique.keys>
            <concurrent>false</concurrent>
            <build.without.logging>true</build.without.logging>
          </path.value.index>
          <path.value.index>
            <name>file_path</name>
            <path>/{urn:opentext:ia:schema:sample:animal:1.0}animals/{urn:opentext:ia:schema:sample:animal:1.0}animal/file_path&lt;STRING>
            </path>
            <compressed>false</compressed>
            <unique.keys>false</unique.keys>
            <concurrent>false</concurrent>
            <build.without.logging>true</build.without.logging>
          </path.value.index>
        </indexes>
      </data>
      <data>
        <id>pdi.aiu.id</id>
        <select.query>
          <![CDATA[
            declare namespace n = "urn:opentext:ia:schema:sample:animal:1.0";
            for $animal in /n:animals/n:animal
            return ($animal, $animal/text())
          ]]>
        </select.query>
      </data>
      <data>
        <id>pdi.aiu.cnt</id>
        <select.query>
          <![CDATA[
            declare namespace n = "urn:opentext:ia:schema:sample:animal:1.0";
            count(/n:animals/n:animal)
          ]]>
        </select.query>
      </data>
      <data>
        <id>pdi.pkeys</id>
        <pkey attr="string01">
          <![CDATA[
            declare namespace n = "urn:opentext:ia:schema:sample:animal:1.0";
            let $animals := (for $animal in /n:animals/n:animal/text()
            order by $animal
            return $animal)
            return fn:upper-case(fn:substring($animals[1], 1, 1))
          ]]>
        </pkey>
        <pkey attr="string02">
          <![CDATA[
            declare namespace n = "urn:opentext:ia:schema:sample:animal:1.0";
            let $animals := (for $animal in /n:animals/n:animal/text()
            order by $animal descending
            return $animal)
            return fn:upper-case(fn:substring($animals[1], 1, 1))
          ]]>
        </pkey>
      </data>
    </datas>

ingest:
  default: true
#  xml: null

